#12.1、概念
     Java的基本理念是“构建不佳的代码不能运行”。
    发现错误的理想实际是在编译阶段，也就是在你试图运行程序之前。然而，编译期间并不
    能找错所有错误，余下的问题必须在运行期间解决。这就需要错误源能通过某种方式，把适
    当的信息传递给某个接收者——高接收者知道如何正确处理改错误。
     改进的错误恢复机制是提供代码健壮性的最强有力的方式。Java使用异常来提供一致的错误
    报告模型，使得构建能够与客户端代码可靠的沟通问题。
     C以及其他早期语言常常具有多种错误处理模式，这些模式往往建立在约定俗成的基础之上，
    而并不属于语言的一部风。对于构建大型、健壮、可维护的程序而言，这种错误处理模式已
    经成为了主要障碍。
     解决的办法是，用强制规定的形式来消除错误处理过程中随心所欲的因素。C++的异常处理
    机制基于Ada，java中的异常处理则是建立在C++的基础之上。
     “异常”这个词有，“我对此感到意外”的意思，问题出现，你也许不知怎么处理，但不能置之
    不理。你需要停下来交给可处理的环境中。
     使用异常所带来的明显好处是，它往往能够降低错误处理代码的复杂度。
    
#12.2、基本异常
     异常情形（exceptional condition）是指阻止当前方法或作用域继续执行的问题。
     异常使得我们可以将每件事都当作一个事务来考虑，而异常可以看护这些事物的底线“......
    事务的基本保障是我们所需的在分布式计算中的异常处理。事务是计算机中的合同法，如果出
    现了问题，我们只需要放弃整个计算。”
##12.2.1、异常参数
    与使用Java中的其他对象一样，我们总是用new在堆上创建异常对象，这也伴随着存储空间的
    分配和构造器的调用。所有标准异常类都有两个构造器：一个是默认构造器；另一个是接受字
    符串作为参数，以便能把相关信息放入异常对象的构造器：
        throw new NullPointerException("t = null")
#12.3、捕获异常
    要明白一场是如何被捕获的，必须首先理解监控区域（guarded region）的概念。他是一段
    可能产生异常的代码，并且后面跟着处理这些异常的代码。
##12.3.1、try块
    如果在方法内部抛出了异常（或者在方法内部调用的其他方法抛出了异常），这个方法将在抛
    出异常的过程中结束。要是不希望方法就此结束，可以在方法内设置一个特殊的块来捕获异常
    。因此在这个快里“尝试”各种（可能产生的异常）方法调用，所以称为try块。他是跟在try关
    键字之后的普通程序块：
        try{
            //code that might generate exceptions
        }
##12.3.2、
    当然，抛出的异常必须在某处得到处理。这个“地点”就是异常处理程序，而且针对每个要捕获
    的异常，的准备相应的处理程序。异常处理程序紧跟在try块之后，以关键字catch表示：
        try{
            //code that might generate exceptions
        }catch(Type1 e){
            //Handle exceptions of Type1
        }catch(Type2 e){
            //Handle exceptions of Type2
        }
     终止与恢复
     异常处理理论上有两种一本模型。Java支持终止模型（他是Java和C++所支持的模型）。在这种模型中，将假设错误非常关键，
     以至于程序无法返回到异常发生的异常发生的地方继续执行。一旦异常被抛出，就表明错误已无法挽回，也不能回来继续执行。
     另一种称为恢复模型。意思是异常处理程序的工作是修正错误，然后重新尝试调用出错的方法，并认为第二次能成功。对于恢复
     模型，通常希望异常被处理之后能继续执行程序。
#12.4、创建自定义异常
    不必拘泥于java中已有的异常类型。java提供异常体系不可能预见所有的希望加以报告的错误，所以可以自己定义异常类来表示
    程序中可能会遇到的特定问题。
    要定义异常类，必须从已有的异常类继承，最好是选择意思相近的异常类继承（不过这样的异常并不容易找）。建立新的异常类
    最简单的方法就是让编译器为你产生默认构造器，所以这几乎不用写多少代码
```java
package com.bai.chap12;

/**
 * @Author:liuBai
 * @Time : 2021/6/21 11:11
 */
class SimpleException extends Exception {



}


public class InheritingException{

    public void f() throws SimpleException{
        System.err.println("Throw SimpleException from f()");
        throw new SimpleException();
    }

    public static void main(String[] args) {
        InheritingException sed = new InheritingException();
        try {
            sed.f();
        } catch (SimpleException e) {
            System.out.println("Caught it!");
        }
    }

}
```
    本例中不会得到像SimpleException(String)这样的构造器，这种构造器不实用。你将看到对异常来说，最重要的部分就是类名
```java
package com.bai.chap12;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Author:liuBai
 * @Time : 2021/6/21 11:24
 */
class MyException extends Exception {

    public MyException(){}
    public MyException(String msg){super(msg);}

}

public class FullConstructors{

    public static final Logger LOGGER = LoggerFactory.getLogger(FullConstructors.class);

    public static void f() throws MyException{
        System.out.println("Throwing MyException from f()");
        throw new MyException();
    }

    public static void g() throws MyException{
        System.out.println("Throwing MyException from g()");
        throw new MyException("Originated in g()");
    }

    public static void main(String[] args) {
        try {
            f();
        } catch (MyException e) {
            e.printStackTrace(System.out);
            LOGGER.error("错误信息:",e);
        }   
        try {
            g();
        } catch (MyException e) {
            e.printStackTrace(System.out);
        }
    }

}

```
    新增的代码不长：两个构造器定义了MyException类型对象的创建方式。对于第二构造器，使用super
    关键字明确调用了其基类构造器，它接受了一个字符串作为参数。
##12.4.1、异常与记录日志
        你可能还想使用java.util.logging工具将输出记录到日志中。尽管记录日志的全部细节是在
    http://MindView.net/Books/BetterJava的补充材料中介绍的，但是这里所使用的基本的日志记
    录功能还是相当简单易懂的：
```java
package com.bai.chap12;


import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.logging.Logger;

class LoggingException extends Exception{
    private static Logger logger = Logger.getLogger("LoggingException");

    public LoggingException(){
        StringWriter trace = new StringWriter();
        printStackTrace(new PrintWriter(trace));
        logger.severe(trace.toString());
    }
}

/**
 * @Author:liuBai
 * @Time : 2021/7/7 14:50
 */
public class LoggingExceptions {

    public static void main(String[] args) {
        try{
            throw new LoggingException();
        }catch (LoggingException e){
            System.err.println("Caught "+e);
        }
        try{
            throw new LoggingException();
        }catch (LoggingException e){
            System.err.println("Caught "+e);
        }
    }

}

```
        静态的Logger.getLogger()方法创建了一个String参数相关联的Logger对象（通常与错误相关的包
    名和类名），这个Logger对象会将其输出发送到System.err。像Logger写入的最简单方式就是直接调用与
    与日志记录消息的级别相关联的方法，这里使用的sereve()。为了产生日志记录消息，我们欲获取异常抛
    出处的栈轨迹，但是printStackTrance()不会默认的产生字符串。为了获取字符串，我们需要使用重载的
    printStackTrace()方法，他接受一个java.io.PrintWriter对象作为参数（这些都将在18章中详细解释）
    。如果我们将一个java.io.StringWriter对象传递给这个PrintWriter的构造器，那么通过调用toString()
    方法，就可以将输出抽取为一个String。
        尽管由于LoggingException将所有记录日志的基础设施都构建在异常自生中，是的它所使用的方法非
    常方便，并因此不需要客户端程序员的干预就可以自动运行，但是更常见的情形是我们需要捕获和记录其他
    人编写的异常，因此我们必须在异常处理程序中生成日志消息：
```java
package com.bai.chap12;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.logging.Logger;

/**
 * @Author:liuBai
 * @Time : 2021/7/7 15:19
 */
public class LoggingExceptions2 {

    private static Logger logger = Logger.getLogger("LoggingExceptions2");

    static void logException(Exception e){
        StringWriter trace = new StringWriter();
        e.printStackTrace(new PrintWriter(trace));
        logger.severe(trace.toString());
    }

    public static void main(String[] args) {
        try{
            throw new NullPointerException();
        }catch (NullPointerException e){
            logException(e);
        }
    }

}

```
        还可以更进一步的自定义异常，比如加入额外的构造器和成员：
```java
package com.bai.chap12;

class MyException2 extends Exception{
    private int x;
    public MyException2(){

    }
    public MyException2(String msg){
        super(msg);
    }
    public MyException2(String msg,int x){
        super(msg);
        this.x = x;
    }
    public int val(){
        return x;
    }
    public String getMessage(){
        return "Detail Message: "+x+" "+super.getMessage();
    }
}

/**
 * @Author:liuBai
 * @Time : 2021/7/7 15:25
 */
public class ExtraFeatures {

    public static void f() throws MyException2{
        System.out.print("Throwing MyException2 from f()");
        throw new MyException2();
    }
    public static void g() throws MyException2{
        System.out.print("Throwing MyException2 from g()");
        throw new MyException2("Originated in g()");
    }
    public static void h() throws MyException2{
        System.out.print("Throwing MyException2 from h()");
        throw new MyException2("Originated in g()",47);
    }

    public static void main(String[] args) {
        try{
            f();
        }catch (MyException2 e){
            e.printStackTrace(System.out);
        }
        try{
            g();
        }catch (MyException2 e){
            e.printStackTrace(System.out);
        }
        try{
            h();
        }catch (MyException2 e){
            e.printStackTrace(System.out);
            System.out.println("e.val()="+e.val());
        }
    }

}

```
#12.5、
